# application.yml

spring:
  datasource:
    mysqldb:
      username: test-crm
      password: DispC_crm_3142
      jdbc-url: jdbc:mysql://${MYSQL_HOST:10.157.93.227}:3306/test-crm-01?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
    dwdb:
      username: test_crm2
      password: test_crm_123
      jdbc-url: jdbc:postgresql://${GAUSSDB_HOST:10.157.93.151}:25308/db_test_crm?useUnicode=true&characterEncoding=utf8&currentSchema=mscm_gg_crm
      driver-class-name: org.postgresql.Driver

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #typeAliasesPackage: com.lxg.springboot.dao.mybatisplus
  global-config:
    banner: true
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true

server:
  error:
    whitelabel:
      enabled: false